# Golang CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-go/ for more details
version: 2
jobs:
  build:
    docker:
      - image: circleci/golang:1.8
#      - image: circleci/mysql:5.7.18
#        environment:
#          MYSQL_DATABASE: "app"
#          MYSQL_ALLOW_EMPTY_PASSWORD: "yes"
#          MYSQL_ROOT_HOST: "%"

    working_directory: /go/src/github.com/Chyroc/gor
    steps:
      - checkout
      - run: echo $PWD
      - run: echo ls -al
      - run: go get -u github.com/rakyll/gotest
      - run: go get -u github.com/alecthomas/gometalinter
      - run: gometalinter --install

      - run: ./.circleci/check_code_style.sh
      - run: gometalinter --config=./.circleci/gometalinter_config.json ./...
      - run: gotest $(go list ./... | grep -v /vendor | grep -v /examples)